on:
  push:
    branches:
      - develop
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'chore/**'
jobs:
  chromatic-deployment:
    steps:
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
