name: Test
on:
  push:
    branches: main
  pull_request:
    branches-ignore: main

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test coverage
        run: yarn test:coverage
